# Deployment database.yml
login: &login
  adapter: mysql2
  username: americasfs
  password: PuAaxB764m
  socket: /var/run/mysqld/mysqld.sock

production:
  database: americasfarmstand
  <<: *login

development:
  database: americasfarmstand
  <<: *login

staging:
  database: americasfarmstand
  <<: *login
